name: Django CI/CD Pipeline

on:
  push:
    branches:
      - main # Trigger deployment on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" # Adjust as per your Django project

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH Key & Deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          # Create the SSH key file
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > deploy_key.pem
          chmod 600 deploy_key.pem

          # Ensure .ssh directory exists
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

          # Add the server to known hosts to avoid SSH confirmation prompt
          ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

          # Connect to the server and deploy
          ssh -i deploy_key.pem -o ServerAliveInterval=60 $SERVER_USER@$SERVER_IP << 'EOF'
            set -e  # Exit on any error
            
            # Navigate to the project directory
            cd /home/ubuntu/ec2-deployment

            # Pull the latest changes from GitHub
            git pull origin main

            # Activate virtual environment
            source .venv/bin/activate  # Ensure this matches your build job

            # Install dependencies
            pip install --upgrade pip
            pip install -r requirements.txt

            # Restart the Django application
            sudo systemctl restart djangp-app.service
          EOF
